module.exports = {
    'vue/no-async-in-computed-properties': 'error',
    'vue/no-dupe-keys': 'error',
    'vue/no-duplicate-attributes': [
        'error',
        {
            'allowCoexistClass': true,
            'allowCoexistStyle': true
        }
    ],
    'vue/no-parsing-error': 'error',
    'vue/no-reserved-keys': 'error',
    'vue/no-shared-component-data': 'error',
    'vue/no-side-effects-in-computed-properties': 'error',
    'vue/no-template-key': 'error',
    'vue/no-textarea-mustache': 'error',
    'vue/no-unused-components': 'error',
    'vue/no-unused-vars': 'error',
    'vue/no-use-v-if-with-v-for': ['error', { 'allowUsingIterationVar': true }],
    'vue/require-component-is': 'error',
    'vue/require-prop-type-constructor': 'error',
    'vue/require-render-return': 'error',
    'vue/require-v-for-key': 'error',
    'vue/require-valid-default-prop': 'error',
    'vue/return-in-computed-property': 'error',
    'vue/use-v-on-exact': 'error',
    'vue/valid-template-root': 'error',
    'vue/valid-v-bind': 'error',
    'vue/valid-v-cloak': 'error',
    'vue/valid-v-else-if': 'error',
    'vue/valid-v-else': 'error',
    'vue/valid-v-for': 'error',
    'vue/valid-v-html': 'error',
    'vue/valid-v-if': 'error',
    'vue/valid-v-model': 'error',
    'vue/valid-v-on': 'error',
    'vue/valid-v-once': 'error',
    'vue/valid-v-pre': 'error',
    'vue/valid-v-show': 'error',
    'vue/valid-v-text': 'error',
    'vue/attribute-hyphenation': 'error',
    'vue/html-closing-bracket-newline': [
        'error',
        { 'singleline': 'never', 'multiline': 'never' }
    ],
    'vue/html-closing-bracket-spacing': 'error',
    'vue/html-end-tags': 'error',
    'vue/html-indent': 'error',
    'vue/html-quotes': ['error', 'double'],
    'vue/html-self-closing': 'error',
    'vue/max-attributes-per-line': [
        'error',
        { 'singleline': 1, 'multiline': { 'max': 1, 'allowFirstLine': true }}
    ],
    'vue/multiline-html-element-content-newline': 'error',
    'vue/mustache-interpolation-spacing': ['error', 'always'],
    'vue/name-property-casing': ['error', 'kebab-case'],
    'vue/no-multi-spaces': 'error',
    'vue/no-spaces-around-equal-signs-in-attribute': 'error',
    'vue/no-template-shadow': 'error',
    'vue/prop-name-casing': ['error', 'camelCase'],
    'vue/require-default-prop': 'off',
    'vue/require-prop-types': 'error',
    'vue/singleline-html-element-content-newline': 'error',
    'vue/v-bind-style': ['error', 'shorthand'],
    'vue/v-on-style': ['error', 'shorthand'],
    'vue/attributes-order': 'error',
    'vue/no-v-html': 'error',
    'vue/order-in-components': 'error',
    'vue/this-in-template': ['error', 'never'],
    'vue/array-bracket-spacing': [
        'error',
        'always',
        { 'singleValue': false, 'objectsInArrays': false, 'arraysInArrays': false }
    ],
    'vue/arrow-spacing': 'error',
    'vue/block-spacing': 'error',
    'vue/brace-style': ['error', 'stroustrup'],
    'vue/camelcase': ['error', { 'properties': 'never' }],
    'vue/comma-dangle': ['error', 'always-multiline'],
    'vue/component-name-in-template-casing': ['error', 'kebab-case'],
    'vue/dot-location': 'off',
    'vue/eqeqeq': ['error', 'always'],
    'vue/key-spacing': [
        'error',
        { 'beforeColon': false, 'afterColon': true, 'mode': 'minimum' }
    ],
    'vue/keyword-spacing': ['error', { 'before': true, 'after': true }],
    'vue/match-component-file-name': 'off',
    'vue/no-boolean-default': 'off',
    'vue/no-deprecated-scope-attribute': 'error',
    'vue/no-empty-pattern': 'error',
    'vue/no-restricted-syntax': 'off',
    'vue/object-curly-spacing': ['error', 'always'],
    'vue/require-direct-export': 'off',
    'vue/script-indent': ['error', 2, { 'switchCase': 1 }],
    'vue/space-infix-ops': 'error',
    'vue/space-unary-ops': ['error', {'words': true, 'nonwords': false}],
    'vue/v-on-function-call': 'off',
    'vue/v-slot-style': 'error',
    'vue/valid-v-slot': 'error',
};
